# Generated by Django 4.2.6 on 2023-11-17 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(default='n.a.', max_length=20)),
                ('model_name', models.CharField(default='n.a.', max_length=20)),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
