# Generated by Django 4.2.6 on 2023-10-22 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_alter_historyproduct_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historyproduct",
            name="product",
        ),
    ]
