# Generated by Django 4.2.6 on 2023-10-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_historyproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_1",
            field=models.ImageField(blank=True, upload_to="product_pics"),
        ),
        migrations.AddField(
            model_name="product",
            name="image_2",
            field=models.ImageField(blank=True, upload_to="product_pics"),
        ),
        migrations.AddField(
            model_name="product",
            name="image_3",
            field=models.ImageField(blank=True, upload_to="product_pics"),
        ),
    ]
