# Generated by Django 4.2.6 on 2023-11-17 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_val', models.CharField(choices=[('1', 'Completely dissatisfied'), ('2', 'Dissatisfied'), ('3', 'Acceptable'), ('4', 'Satisfied'), ('5', 'Very satisfied')], default=5, max_length=1)),
                ('description', models.TextField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
