# Generated by Django 4.2.6 on 2023-10-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_historyproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(default="n.a.", max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="model_name",
            field=models.CharField(default="n.a.", max_length=20),
        ),
    ]
