# Generated by Django 4.2.6 on 2023-10-18 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_historycategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoryCategory",
        ),
    ]
