# Generated by Django 4.2.6 on 2023-10-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0004_historycategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="special_character",
            field=models.CharField(default="restart_alt", max_length=20),
        ),
    ]
