# Generated by Django 4.2.6 on 2023-11-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="description",
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating_val",
            field=models.CharField(
                choices=[
                    ("1", "Completely dissatisfied"),
                    ("2", "Dissatisfied"),
                    ("3", "Acceptable"),
                    ("4", "Satisfied"),
                    ("5", "Very satisfied"),
                ],
                default=5,
                max_length=1,
            ),
        ),
    ]
